### PR TITLE
Fix React 15.5 deprecation warnings

### PR DESCRIPTION
**Pull request by senguidanos**
Imports PropTypes from prop-types to fix react 15.5 deprecations and handles the move of ReactTestUtils under react-dom 15.5.

### CODE REVIEW

**Comment by randomdevpete** [comment]
+1, this would fix #8

**Comment by udisun** [comment]
what's going on with this fix? why isn't it merged?
is the owner dead? :) (hope not)

**Comment by spmebrge** [comment]
Is this able to be merged?
@senguidanos

**Comment by moubi** [comment]
We have the fix in now. Thanks the help guys.

**Pull request closed without merging**
